plugins:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
      tests_patterns:
        - app/src/test/**
        - app/src/androidTest/**
